### ISSUE TITLE
Improvements over Veldrid

### ISSUE THREAD

**Issue by xoofx** [XenoAtom/XenoAtom.Graphics#1]
There are several [pull-requests](https://github.com/veldrid/veldrid/pulls) and [issues](https://github.com/veldrid/veldrid/issues) raised on Veldrid.

Some are important bug fixes and improvements that I might want to integrate. Work should be more manageable as I only have to manage Vulkan.

Need to take the time to list here which one I would like to add to my list. For now for the PR:

- [x] https://github.com/veldrid/veldrid/pull/500 (Fixed by 79dd2b24427f9b848f4868324f4c1faeff70bfd3)
- [x] https://github.com/veldrid/veldrid/pull/495 (Fixed by 81240a994c55b2fa5c0a9285f12a0e2864b282f3)
- [x] https://github.com/veldrid/veldrid/pull/462 (Fixed by d49b341fb2d1c7689e1be27a7661e603e8e9aae4)
- [x] https://github.com/veldrid/veldrid/pull/450 (Fixed by 13289aa9946613bb659a0b81b71b5e90f445cbbd)
- [x] https://github.com/veldrid/veldrid/pull/406 (Fixed below)
- [x] https://github.com/veldrid/veldrid/pull/396 (Fixed by 75fe7d040dd3941f0e3e4274f80bfd96400b731e and 3e3b31cfa2ea93641b850ddfd1133bd57d9f641b)
- [x] https://github.com/veldrid/veldrid/pull/368 (Fixed by 1593f0fdf9f81835631dd652c330e3279ae6f4f6)
- [x] https://github.com/veldrid/veldrid/issues/430 (Fixed by 1593f0fdf9f81835631dd652c330e3279ae6f4f6)
- [x] https://github.com/veldrid/veldrid/issues/387 (Fixed by e6b89d39f89d203ac92b57014efeac75329591b0)
- [ ] https://github.com/veldrid/veldrid/pull/363
- [ ] https://github.com/veldrid/veldrid/pull/357
- [ ] https://github.com/veldrid/veldrid/pull/350

Whenever possible, add tests, as it was quite valuable to have already tests in Veldrid to double check the migration to `XenoAtom.Interop.vulkan`.

List of things I would like to improve:

- [x] First pass of adding support for Nullable reference types (fixed via 9f4a80125c6d37aa1a33231edd1a490a4ad996a7)
- [x] Simplify code for image layout transitions (via 4980977290f7d62fed736ac0b6b78b19cc873e53)
- [x] Improve debugging layers, switch to `VK_EXT_debug_utils` (via 52cf1ebd31616d6633332a95ba90ca8f22413b1e)
- [x] Add support for multiple GPU (e.g discrete and iGPU)
- [x] Add better support to activate validation layers (there are currently warnings)
- [x] Some cleanup of the code
- [x] Use more modern C# features (Mostly Span and maybe some new C# 12 language features)
- [x] Improve further memory allocator - using a TLSF/VMA like allocator (Fixed by #2)
- [x] Add support for explicit command pool management (#4)
- [ ] Improve management of descriptor sets, see #3 
- [ ] API cleanup
- [ ] Reduce allocations (Use more `XenoAtom.Collections` internally instead of `System.Collections`)
- [x] Once done, might promote [XenoAtom.Interop.vulkan](https://github.com/XenoAtom/XenoAtom.Interop/tree/main/src/vulkan) to a stable 1.0.0 as its integration looks good here
